### ISSUE TITLE
processor.set_value() should allow values like list or dict

### ISSUE THREAD

**Issue by am21** [wwkimball/yamlpath#118]
Currently `processor.set_value()` converts a list to a string when assigning to a node.

would like the ability to set the value to a list.

**Comment by wwkimball** [comment]
This is both a common request and a misconception.  When it comes to YAML, there is no such thing as simply setting a list or map to a node.  Such operations can only be safely and robustly performed as part of a complex merge process that is savvy to YAML Anchors and Aliases, because every list or map merge can contain -- and even define -- them.  For this reason, I developed the Merger class and its accompanying reference implementation, the `yaml-merge` command.

Please refer to the documentation for a brief on using Merger as well as https://github.com/wwkimball/yamlpath/issues/56#issuecomment-640326360 for a deeper dive into this frequent request.

**Comment by am21** [comment]
Got it. I am trying to put together the smallest example to use the libraries to do the merge. Here's what I have so far:
```python
import ruamel.yaml as yaml
import logging
from yamlpath.merger import Merger, MergerConfig

import warnings
warnings.simplefilter("ignore", yaml.error.UnsafeLoaderWarning)

lhs = """
top:
  key: foo
"""
rhs = ["foo", "bar"]

class Namespace:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

lhs = yaml.load(lhs, Loader=yaml.Loader)
log = logging.getLogger("")

args = Namespace(mergeat="/top/key", arrays="right", hashes="right", aoh="right")
merger = Merger(log, lhs, MergerConfig(log, args))
merger.merge_with(rhs)
merger.prepare_for_dump(yaml)
print(yaml.dump(merger.data))
```
and all I get as a result is `top: {key: "['foo', 'bar']"}`, i.e. the list is merged as a string. I'm probably missing something obvious, but I can't see it :-)

**Comment by wwkimball** [comment]
It looks like you're working a lot harder than you need to.  :)  A crash-course minimum code example (some routine/boilerplate code is left to the reader) is at https://github.com/wwkimball/yamlpath#merging-documents.  For a full example, check out the unit tests.  The most concise example could be `test_merge_with_defaults_simple_hash`, at https://github.com/wwkimball/yamlpath/blob/master/tests/test_merger_merger.py#L99-L146.
