### ISSUE TITLE
DOCUMENTATION:  More detail needed for library use

### ISSUE THREAD

**Issue by ltagliamonte-dd** [wwkimball/yamlpath#131]
Hello! i'm trying to use this library to read a yaml file and update some values in it.
tbh I'm struggling a bit with the doc, (would love to have a really simple example with no logger, console, etc..) and when i'm trying to read the file i get this error:
```
 File "/Users/luigi.tagliamonte/Projects/scripts/update_tier.py", line 58, in update_clusters
    (yaml_data, doc_loaded) = get_yaml_data(yaml, None, rel_file_path)
  File "/usr/local/lib/python3.8/site-packages/yamlpath/func.py", line 25, in get_yaml_data
    return Parsers.get_yaml_data(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yamlpath/common/parsers.py", line 110, in get_yaml_data
    yaml_data = parser.load(fhnd)
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 109, in load
    load_warning('load')
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 55, in load_warning
    warnings.warn(message, YAMLLoadWarning, stacklevel=3)
yaml.YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

**Comment by wwkimball** [comment]
I'd be happy to help, but I need some more information.  From what you've provided, I'm unable to assess what is going on.  Please be sure to fill out the issue template when you open issues.  I really do need all of that information to get a clear picture of what you are facing.

As for what I can see, you appear to have made some mistakes in your setup.  Please refer to the [Basic Usage:  Libraries section of the README file](https://github.com/wwkimball/yamlpath/blob/master/README.md#basic-usage--libraries).  You seem to be using an invalid or improperly configured YAML parser -- I can't precisely tell what is wrong with your parser because you've omitted that setup code -- and you've failed to pass a mandatory logging facility.  Without a logger, you'll suppress vital information whenever things go bad, or you'll force unhelpful stack-dumps in front of your users.  I do my best to ensure that error messages are meaningful and contain remedy information, wherever possible

Please try to copy-paste the sample code from the documentation and run that verbatim.  You should find that it works without any issues.  Then, tweak it to fit your specific use-case.

**Comment by wwkimball** [comment]
I have greatly expanded [the Wiki documentation for the core library files](https://github.com/wwkimball/yamlpath/wiki/Python-Library).  Please let me know if you need me to delve even deeper into any of the material.

Thanks for any and all feedback!
