### ISSUE TITLE
Add support for YAML timestamp values with documentation

### ISSUE THREAD

**Issue by AndydeCleyre** [wwkimball/yamlpath#181]
**Is your feature request related to a problem? Please describe.**
I'm using a `Processor` to replace some string values with other types. I can't seem to set a YAML date value using the `Processor`, but it does work using `ruamel.yaml`'s `CommentedMap`'s `dict` interface.

```python
#!/usr/bin/env python3
from yamlpath import Processor as YPProcessor
from yamlpath.wrappers import ConsolePrinter as YPConsolePrinter
from yamlpath.common import Parsers as YPParsers
from types import SimpleNamespace
from json import dumps as jdumps
from datetime import date


if __name__ == '__main__':

    # Start with an untyped date
    data = {'when': '2022-09-23'}

    # Get a CommentedMap "doc" and Processor, "surgeon"
    YAML_EDITOR = YPParsers.get_yaml_editor()
    log = YPConsolePrinter(SimpleNamespace(quiet=True, verbose=False, debug=False))
    doc, success = YPParsers.get_yaml_data(YAML_EDITOR, log, jdumps(data), literal=True)
    surgeon = YPProcessor(log, doc)

    # Try replacing the string date with a yaml-friendly date object:

    print(doc)  # ordereddict([('when', '2022-09-23')])
    d = date.fromisoformat(doc['when'])
    print(d)    # datetime.date(2022, 9, 23)

    doc['when'] = d
    print(doc)  # ordereddict([('when', datetime.date(2022, 9, 23))])

    try:
        surgeon.set_value('/when', d)
    except TypeError:
        print("'datetime.date' object cannot be interpreted as an integer")

```

**Describe the solution you'd like**
I would like an example added to the wiki, of setting a given yamlpath node to a YAML date value.

**Describe alternatives you've considered**
Even though using `doc[key] = d` works, I'm getting arbitrary paths from a `Processor.get_nodes` result, and AFAIK `Processor.set_value` is the only way to modify data at arbitrary yaml paths.

**Additional context**

```python
TypeError                                 Traceback (most recent call last)
----> 1 surgeon.set_value('/when', d)

File ~/.local/share/venvs/1be7b478d580cac73a8bca0e01d57a97/venv/lib/python3.10/site-packages/yamlpath/processor.py:187, in Processor.set_value(self, yaml_path, value, **kwargs)
    180 self.logger.debug(
    181     "Processor::set_value:  Seeking optional node at {}."
    182     .format(yaml_path)
    183 )
    184 for node_coord in self._get_optional_nodes(
    185     self.data, yaml_path, value
    186 ):
--> 187     self._apply_change(yaml_path, node_coord, value,
    188         value_format=value_format, tag=tag)

File ~/.local/share/venvs/1be7b478d580cac73a8bca0e01d57a97/venv/lib/python3.10/site-packages/yamlpath/processor.py:287, in Processor._apply_change(self, yaml_path, node_coord, value, **kwargs)
    284         return
    286 try:
--> 287     self._update_node(
    288         node_coord.parent, node_coord.parentref, value,
    289         value_format, tag)
    290 except ValueError as vex:
    291     raise YAMLPathException(
    292         "Impossible to write '{}' as {}.  The error was:  {}"
    293         .format(value, value_format, str(vex))
    294         , str(yaml_path)) from vex

File ~/.local/share/venvs/1be7b478d580cac73a8bca0e01d57a97/venv/lib/python3.10/site-packages/yamlpath/processor.py:2589, in Processor._update_node(self, parent, parentref, value, value_format, value_tag)
   2587 else:
   2588     change_node = parent[parentref]
-> 2589 new_node = Nodes.make_new_node(
   2590     change_node, value, value_format, tag=value_tag)
   2592 self.logger.debug(
   2593     f"Changing the following <{value_format}> formatted node:",
   2594     prefix="Processor::_update_node:  ",
   2595     data={ "__FROM__": change_node, "___TO___": new_node })
   2597 recurse(self.data, parent, parentref, change_node, new_node)

File ~/.local/share/venvs/1be7b478d580cac73a8bca0e01d57a97/venv/lib/python3.10/site-packages/yamlpath/common/nodes.py:167, in Nodes.make_new_node(source_node, value, value_format, **kwargs)
    165         new_node = new_type(new_value, anchor=source_node.anchor.value)
    166     elif new_type is not type(None):
--> 167         new_node = new_type(new_value)
    169 # Apply a custom tag, if provided
    170 if "tag" in kwargs:
```

**Comment by AndydeCleyre** [comment]
An alternative for some cases might to format them as strings to then print them as bare, but I wish to keep them in some kind of date format, so I can serialize this modified document in other formats with appropriate type conversions.

**Comment by wwkimball** [comment]
This turns out to be a deficiency in yamlpath.  Per [it's own tests](https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/_test/test_datetime.py), ruamel.yaml supports "a subset of the ISO8601 format" for date/time values per http://yaml.org/type/timestamp.html (with indicated caveats).  However, yamlpath fails to extend this support to end-users on behalf of ruamel.yaml.

I'll add a new format for datetime values.  SInce there doesn't appear to be an explicit ruamel.yaml Scalar* data type for datetime values, this might be tricky.  I'll do my best; just note that this will be limited to what ruamel.yaml supports.

**Comment by wwkimball** [comment]
Adding robust date and timestamp handling just got blocked by https://sourceforge.net/p/ruamel-yaml/tickets/440/.  I cannot reliably offer date and timestamp capabilities because ruamel.yaml has a blocking issue wherein anchors are lost when used with nodes of these data types.

**Comment by wwkimball** [comment]
Anthon (author of ruamel.yaml) came through with an emergency patch for this issue.  I'm working hard to get this issue resolved and released ASAP.

**Comment by wwkimball** [comment]
I've released version 3.6.6 which includes support for ISO8601 dates and timestamps, per https://yaml.org/type/timestamp.html.  However, https://sourceforge.net/p/ruamel-yaml/tickets/440/ is still open against ruamel.yaml for this support, so this is somewhat tepid support.  This is because I'm not especially happy with how ruamel.yaml handles these values.  While the value is in memory in the ruamel.yaml DOM, it will be UTC-normalized as a time-zone naive datetime.datetime (wrapped in a new AnchoredTimeStamp instance).  In order to de-normalize the value and "get back out what you put in" (when using time-zone aware source data), pass the DOM value through a new `Nodes.get_timestamp_with_tzinfo(data: AnchoredTimeStamp) -> datetime` static method.  Because closing that ruamel.yaml ticket will likely incur a significant rework of yamlpath code, I'm only offering minimal support for now.  For example, I'm not doing any automatic detection of date or timestamp values at this time; you'll need to specify `--format=date` and `--format=timestamp` when setting these values via yaml-set.  When this issue closes, I intend to add support for more "loose" formats of date and timestamp values in addition to automatic detection.  For now, be sure to use supported ISO8601 values and manually specify the value format.

**Comment by wwkimball** [comment]
Please skip version 3.6.6.  The Python package builder (setuptools) failed to pick up the required ruamel.yaml patch file.  Release 3.6.7 -- which I'm releasing right now -- should include the missing code.

**Comment by AndydeCleyre** [comment]
Thank you, I was able to use the new `AnchoredDate` and `AnchoredTimeStamp` objects successfully!

I'm currently checking objects to see if they are instances of `yamlpath.patches.timestamp.AnchoredDate` first, and otherwise checking if they are `ruamel.yaml.timestamp.TimeStamp`, to separate dates from datetimes. I expect in the future I'll need to replace `yamlpath.patches.timestamp.AnchoredDate` with something from `ruamel.yaml` directly.

**Comment by wwkimball** [comment]
That is correct; the code in yamlpath.patches comes directly from Anthon of ruamel.yaml.  He provides that code to me so that I can release fixes in yamlpath before he's ready to release the same fix(es) in the next version of ruamel.yaml.  As such, what is today a `yamlpath.patches.timestamp.Anchored*` will later become a `ruamel.yaml.timestamp.Anchored*`.  Like you, I will also be forced to change my `import`s and drop the relevant patch(es) whenever Anthon releases the next ruamel.yaml version.
