### ISSUE TITLE
Allowing for multiple files to be changed with yaml-set

### ISSUE THREAD

**Issue by aharper273** [wwkimball/yamlpath#53]
If a user has multiple yaml files and would like the value for each key to change uniformly, there doesn't seem to be functionality to support this within yamlpath.

**Describe the solution you'd like**
Allow a user to specify multiple  filesnames and/or use a wildcard.
I.E.
```yaml-set --change=food.salad --values"caesar" foo.yaml bar.yaml```
and 
```yaml-set -change=food.salad --values="Cobb" *.yaml```

Obviously it is possible to find a way to loop as needed, but this this would be a nice feature to be build in.

Also, wanted to say that this is extremely helpful tool and it works wonderfully! Thank you for making it!

**Comment by wwkimball** [comment]
This was a conscious decision because yaml-path "plays nicely" with other tools.  In your case, `find`.  Please try this:  `find /where/your/yaml/files/are/ -type f -name '*.yaml' -exec yaml-set --change=food.salad --values=ceasar {} \;`

Chaining `yaml-path` with `find` gives a much more granular control over which YAML files to affect than a simple skeleton mask can provide.  The possibilities for granular selection become even more interesting when chaining with other tools like `grep`.
