### ISSUE TITLE
Error Updating Negative Floats

### ISSUE THREAD

**Issue by ldedwards** [wwkimball/yamlpath#59]
Hi

When trying to update a negative float value, we get a positive value with an additional leading zero, e.g. 00.9 instead of -0.9.

Steps to reproduce below.

## Operating System

1. Name/Distribution: Linux
2. Version:

## Version of Python and packages in use at the time of the issue.

1. [Distribution](https://wiki.python.org/moin/PythonDistributions):
2. Python Version: 3.7.1
3. Version of yamlpath installed: 2.3.6
4. Version of ruamel.yaml installed: 0.16.10

## Minimum sample of YAML (or compatible) data necessary to trigger the issue

```
---
parameters:
  param1: 0.1
  param2: 0.9
```

## Complete steps to reproduce the issue when triggered via:

1. Command-Line Tools (yaml-get, yaml-set, or eyaml-rotate-keys):  Precise command-line arguments which trigger the defect. 
2. Libraries (yamlpath.*):  Minimum amount of code necessary to trigger the defect.

```
from yamlpath.func import get_yaml_data, get_yaml_editor
from yamlpath import Processor
from yamlpath.wrappers import ConsolePrinter
from ruamel.yaml import YAML

class Args:
  debug = False
  verbose = False
  quiet = True

file = 'test.yaml'
param = '/parameters/param2'
val = -0.9
 
args = Args()
log = ConsolePrinter(args)
 
instance = YAML()
instance.default_flow_style = False
instance.explicit_start = True
 
yaml = get_yaml_editor()
yaml_editor = get_yaml_editor()
yaml_contents = get_yaml_data(yaml_editor, log, file)
 
processor = Processor(log, yaml_contents)
processor.set_value(param, val, value_format= YAMLValueFormats.FLOAT)
 
with open(file, 'w') as cfile:
    yaml_editor.dump(yaml_contents, cfile)
```

## Expected Outcome

```
parameters:
  param1: 0.1
  param2: -0.9
```

## Actual Outcome

```
parameters:
  param1: 0.1
  param2: 00.9
```

**Comment by wwkimball** [comment]
It is curious that a unit test for exactly this case passes; the negative float appears to update within the DOM perfectly as expected.  It is when that DOM is then rendered back to the YAML stream that something unexpected occurs.  I use ruamel.yaml for YAML parsing and rendering and until I dig deeper, I cannot tell whether the reported issue is being caused by my own code or a bug in the ruamel.yaml library.

I accept this as a bug.  I will continue to investigate.  Should the issue be within my own code, I'll turn around a fix ASAP.  If however, the bug is in the underlying ruamel.yaml library, a fix may take considerably longer while we all wait for its author to acknowledge and fix the issue.

Thank you for discovering and reporting this!

**Comment by wwkimball** [comment]
Update:  there is a weird interaction with ruamel.yaml regarding floats wherein its author advises recasting values to ryamel.yaml data-types, in this case to his ScalarFloat() float.  For some reason, that custom type fails to self-identify attributes of float values that are passed in as real floats, losing track of extended attributes like whether they are negative, their precision, length, and such.

I've added a bunch of code in the attached PR to manually discover these extended attributes while constructing the required ScalarFloat() object.  At present however, this only works when you explicitly specify `value_format=YAMLValueFormats.FLOAT` (API) or `--format=float` (CLI).  Failing this, ruamel.yaml crashes due to what looks like an internal bug (comparing an int to a None in a case where the int will never have a value).  I want to pursue this a bit longer to see if I can detect cases when `value_format` or `--format` are not specified for a float value so that ruamel.yaml doesn't crash (because when ruamel.yaml crashes, it looks like YAMLPath crashes to users even though that isn't technically the case).

**Comment by wwkimball** [comment]
I have it sorted out per the PR, and will prepare a release this week.

**Comment by wwkimball** [comment]
This issue is fixed.  Please update to yamlpath version 2.3.7 for the fix.
