### ISSUE TITLE
Request: Docs on creating yaml from scratch, or merging into nothingness

### ISSUE THREAD

**Issue by AndydeCleyre** [wwkimball/yamlpath#70]
**Is your feature request related to a problem? Please describe.**
In the case where the file to be changed via `yaml-set` or `yaml-merge` is either non-existent, empty, or not empty but without any values, the behavior and proper handling is unclear to me.

It seems that some dummy data must be fed in first in these cases, but I may be misunderstanding, because the docs for `yaml-merge` say:

> With the --mergeat (-m) argument, you can direct all RHS content to one or more LHS destinations indicated via YAML Path. This enables users to merge together data fragments or even arbitrary data structure rather than premade, otherwise complete documents. Specifying a YAML Path which matches zero nodes will result in the missing structure being created on-the-fly, if possible.

**Describe the solution you'd like**
I'd appreciate a note from the author on best merge practices when the original document may be empty, nonexistent, or valueless.

**Describe alternatives you've considered**
```console
$ rm -f vars.yml
$ yaml-set -g .newkey -a 5 -F literal vars.yml
ERROR:  File not found:  vars.yml
Please try --help for more information.
$ yaml-merge vars.yml - <<<'newkey: "5"'
ERROR:  File not found:  vars.yml
Please try --help for more information.
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ yaml-merge -m . vars.yml - <<<'newkey: "5"'
ERROR:  File not found:  vars.yml
Please try --help for more information.
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ touch vars.yml
$ yaml-set -g .newkey -a 5 -F literal vars.yml
$ # no stdout/err, but retcode 1
$ yaml-merge vars.yml - <<<'newkey: "5"'
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ yaml-merge -m . vars.yml - <<<'newkey: "5"'
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ printf '%s\n' '---' >vars.yml
$ yaml-set -g .newkey -a 5 -F literal vars.yml
$ # no stdout/err, but retcode 1
$ yaml-merge vars.yml - <<<'newkey: "5"'
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ yaml-merge -m . vars.yml - <<<'newkey: "5"'
CRITICAL:  The first input file, vars.yml, has nothing to merge into.
$ printf '%s\n' 'oldkey: "4"' >>vars.yml
$ yaml-merge vars.yml - <<<'newkey: "5"'
---
oldkey: "4"
newkey: "5"
$ # success!
$ yaml-merge -m . vars.yml - <<<'newkey: "5"'
---
oldkey: "4"
newkey: "5"
$ # success!
$ yaml-set -g .newkey -a 5 -F literal vars.yml
$ # success!
```

**Comment by wwkimball** [comment]
That is certainly an unexpected use-case for these tools, which were made to operate against *existing* YAML/JSON/Compatible files.  😃

There are at least two ways to accomplish your objective (generate new files from scratch):

1. **Wait for the next release of this project.**  As a matter of coincidence, the very next version of yaml-merge happens to allow exactly what you're asking about.  Here's a capture of me trying your exact command against the next version:

```shell
$ cat vars.yml 
cat: vars.yml: No such file or directory

$ yaml-merge --output=vars.yml <<<'newkey: "5"'

$ echo $?
0

$ cat vars.yml 
---
newkey: "5"
```

2. If you cannot wait for the next release (maybe a week, or so?), **create an empty, valid document before using `yaml-set` or `yaml-merge` against it**.  You have already discovered this.  In this case, you've met the requirement that the existing tools can operate only against at least one already-existing files.

I'll accept this as both a documentation request and a soon-to-be-released feature request.

Thanks!

**Comment by AndydeCleyre** [comment]
Thanks! 

1. In your example from the upcoming release, there is no "original" ("LHS") specified. Will it support empty or nonexistent files for that?

2. What's a valid empty file look like? The two forms I tried above didn't cut it, I had to add a dummy variable.

**Comment by wwkimball** [comment]
1. Yes, the future version of `yaml-merge` accepts zero input files as long as it is involved in a "non-TTY session", which is created when you use `|` or `<<<`.  This makes use of the `-` pseudo-file both optional and still valid.
1. That is an interesting question.  On the technical level, a minimum valid file depends on the type of file:

YAML (the YAML spec does mandate the use of a YAML Start-of-Document marker [`---\n`]):
```yaml
---
```

JSON:
```json
{}
```
or:
```json
[]
```

However, `yaml-set` won't write to an empty file.  Instead, it exits with a 1 because it assumes there was an issue reading from the file.  This is yet another unexpected use-case for `yaml-set`; nicely done.  So, for the *present* version of `yaml-set`, a minimum valid file must have at least one data element, be it a key-value pair or an array element.

I'll add "permit writing to minimum-viable YAML/JSON files" as another enhancement for the next release.

Thanks!!

**Comment by wwkimball** [comment]
I just pushed a change to the in-progress feature branch which enables the following to succeed:

```shell
$ echo '---' >empty.yaml; yaml-set --change=/key --value=value empty.yaml && cat empty.yaml
---
key: value
```

This enables `yaml-set` to write content to empty, valid YAML files.

**Comment by wwkimball** [comment]
Interesting note:  If you do the same using `yaml-merge` like this:

```shell
$ echo '---' >empty.yaml; echo "{key: ''}" | yaml-merge empty.yaml
{"key": ""}
```

You get JSON output.  This is because the empty document is indistinguishable between YAML versus JSON but the first RHS document is definitely JSON, so the output infers JSON.  You can pipe in real YAML to cause the inference to select YAML:

```shell
$ echo '---' >empty.yaml; echo -e "---\nkey: ''" | yaml-merge empty.yaml
---
key: ''
```

*Or*, you can just set `--document-format|-D` to either `json` or `yaml` to directly control the output document format.

**Comment by wwkimball** [comment]
I'm tying this off with a bow.  I'm not sure whether I need to add an example for this on the Wiki because with this next release, the desired behavior will be built-in and should be intuitive.  I've further enhanced the output type auto-detection to be sensitive to the output|overwrite file-name extension.  So, for example:

## For files which exist but are **completely** empty
```shell
$ echo '' >empty.yaml; echo "{key: ''}" | yaml-merge --overwrite=empty.yaml && cat empty.yaml
WARNING:  Output file exists and will be overwritten:  empty.yaml
Processing STDIN...
---
key: ''
 
$ echo '' >empty.json; echo "{key: ''}" | yaml-merge --overwrite=empty.json && cat empty.json 
WARNING:  Output file exists and will be overwritten:  empty.json
Processing STDIN...
{"key": ""}
```

## For files which **do not exist**
```shell
$ rm -f empty.*; echo "{key: ''}" | yaml-merge --output=empty.yaml && cat empty.yaml
Processing STDIN...
---
key: ''

$ rm -f empty.*; echo "{key: ''}" | yaml-merge --output=empty.json && cat empty.json
Processing STDIN...
{"key": ""}
```

**Comment by AndydeCleyre** [comment]
This is all beautiful, thank you!
